// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WalkIn",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "WalkIn",
            targets: ["AppModule"],
            bundleIdentifier: "V3.WalkIn",
            teamIdentifier: "S749N6FFP2",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .location),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .motion(purposeString: "Unknown Usage Description"),
                .camera(purposeString: "Unknown Usage Description"),
                .userTracking(purposeString: "Unknown Usage Description")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [

            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)